### ISSUE TITLE
直接运行怎么输出结果全部为0呢

### ISSUE THREAD

**Issue by 670555467** [yeshenpy/ERL-Re2#1]
直接运行，Train_Max,Test_Score等全部为0呢

**Comment by yeshenpy** [comment]
抱歉抱歉，我刚刚看到。你说的这个问题是学习过程中print出来的结果吗？我建议直接看wandb的输出结果，这个是论文中report结果的来源。

也可以提供给我具体信息，我check一下。

**Comment by 670555467** [comment]
> 抱歉抱歉，我刚刚看到。你说的这个问题是学习过程中print出来的结果吗？我建议直接看wandb的输出结果，这个是论文中report结果的来源。
> 
> 也可以提供给我具体信息，我check一下。

你好，我刚入门。parser.add_argument('-EA', help='Use ea', action='store_true',)
parser.add_argument('-RL', help='Use rl', action='store_true')   默认RL和EA为False，怎么修改为True

**Comment by 670555467** [comment]
> 抱歉抱歉，我刚刚看到。你说的这个问题是学习过程中print出来的结果吗？我建议直接看wandb的输出结果，这个是论文中report结果的来源。
> 
> 也可以提供给我具体信息，我check一下。
运行到Frames9983时报错：RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [300, 6]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by yeshenpy** [comment]
你好，
第一个问题，你传入-EA和RL就变为True了，
第二个问题，是因为你的torch版本太高了，需要严格按照我提供的版本构建环境。
有问题随时反馈。
