### ISSUE TITLE
crossover and mutation

### ISSUE THREAD

**Issue by zygalaxy** [yeshenpy/ERL-Re2#2]
Hello, In your code, you are directly using the crossover and mutation from PDERL. Where are the crossover and mutation you mentioned? And how are they applied? Looking forward to your response!

**Comment by yeshenpy** [comment]
Hello, thank you for your attention.

The crossover and mutation in the code are already modified versions. If you compare them, you'll see that they are not consistent with the mutation and crossover in PDERL.

If you have any additional questions or concerns, feel free to leave me a message.
