### ISSUE TITLE
Undiscounted Return

### ISSUE THREAD

**Issue by zygalaxy** [yeshenpy/ERL-Re2#3]
![image](https://github.com/user-attachments/assets/e8db7955-95e6-41c6-bf00-b96a5c52bbaa)
I would like to know which item in the figure corresponds to the Undiscounted Return mentioned in your paper. If none of them are, how can I obtain the Undiscounted Return?

**Comment by yeshenpy** [comment]
If I remember correctly, best_reward refers to the final reward result, which represents the best performance (max) of EA and RL.

**Comment by zygalaxy** [comment]
Thank you for your prompt response. I will close this issue now
